# Configuration for PR Labeler
# https://github.com/actions/labeler

# Add 'documentation' label to any change to docs or markdown files
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.md"
      - "docs/**"
      - "README.*"

# Add 'tests' label to any change to test files
tests:
  - changed-files:
    - any-glob-to-any-file:
      - "tests/**"
      - "**/test_*.py"
      - "**/*_test.py"
      - "pytest.ini"
      - ".coveragerc"

# Add 'dependencies' label to any change to dependency files
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - "pyproject.toml"
      - "requirements*.txt"
      - "uv.lock"
      - "setup.py"
      - "setup.cfg"

# Add 'ci' label to any change to CI/CD files
ci:
  - changed-files:
    - any-glob-to-any-file:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".gitlab-ci.yml"
      - "azure-pipelines.yml"
      - ".circleci/**"

# Add 'python' label to any Python file changes
python:
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.py"
      - "**/*.pyx"
      - "**/*.pyi"

# Add 'config' label to configuration file changes
config:
  - changed-files:
    - any-glob-to-any-file:
      - ".*rc"
      - "*.ini"
      - "*.toml"
      - "*.yml"
      - "*.yaml"
      - ".gitignore"
      - ".gitattributes"