name: Dependency Review
on: 
  pull_request:
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug mode'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          # Fail the action if any vulnerabilities are found
          fail-on-severity: moderate
          # Allow only these licenses (customize as needed)
          allow-licenses: GPL-3.0, MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, Unlicense
          # Deny these licenses
          deny-licenses: AGPL-1.0, AGPL-3.0
